# Generated by Django 4.2.13 on 2024-07-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('available', models.BooleanField(default=True)),
                ('publication_date', models.DateField()),
                ('publisher', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['author'],
            },
        ),
    ]
